Parameters:
  DomainName:
    Type: String
    Description: Domain name to use for infrastructure projects

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub ${DomainName}.

  ApexRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: !ImportValue pipelines-networking:LoadBalancerCanonicalHostedZoneId
        DNSName: !ImportValue pipelines-networking:LoadBalancerDNSName

Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Description: ID of the primary infrastructure hosted zone
    Export:
      Name: !Sub ${AWS::StackName}:HostedZoneId

  HostedZoneNameServers:
    Value: !Join [",", !GetAtt HostedZone.NameServers]
    Description: List of nameservers being used by the primary hosted zone
    Export:
      Name: !Sub ${AWS::StackName}:HostedZoneNameServers