Parameters:
  DomainName:
    Type: String
    Description: Domain name to use for infrastructure projects

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub ${DomainName}.

Outputs:
  DomainName:
    Value: !Ref DomainName
    Description: Primary infrastructure domain name
    Export:
      Name: !Sub ${AWS::StackName}:DomainName
      
  HostedZoneId:
    Value: !Ref HostedZone
    Description: ID of the primary infrastructure hosted zone
    Export:
      Name: !Sub ${AWS::StackName}:HostedZoneId

  HostedZoneNameServers:
    Value: !Join [",", !GetAtt HostedZone.NameServers]
    Description: List of nameservers being used by the primary hosted zone
    Export:
      Name: !Sub ${AWS::StackName}:HostedZoneNameServers